import Head from "next/head";
import { withAuthenticator } from "@aws-amplify/ui-react";
import Layout from "../../components/Layout";

import ProjectsList from "../../features/project/ProjecstList";

function Projects({ user }) {
  return (
    <>
      <Head>
        <title>Luminus Conscious Planning</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout userName={user?.username || ""} pageTitle="Mis Proyectos">
        <ProjectsList />
      </Layout>
    </>
  );
}

export default withAuthenticator(Projects);
