import Head from "next/head";
import { withAuthenticator } from '@aws-amplify/ui-react';
import BudgetCard from "../components/BudgetCard";
import Layout from "../components/Layout";
import { Button,Box } from '@chakra-ui/react'
import Categories from "../components/Categories";
function Home({ signOut, user }) {
  return (
    <div>
      <Head>
        <title>Lumi Budget</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout userName={user.username}>
        <BudgetCard />
        <Categories />
        <Button colorScheme='blue' onClick={signOut}>Cerrar Sesión</Button>
      </Layout>
    </div>
  );
}

export default withAuthenticator(Home);
