import Head from "next/head";
import { withAuthenticator } from "@aws-amplify/ui-react";
import BudgetCard from "../features/wallet/BudgetCard";
import Layout from "../components/Layout";
import Categories from "../features/wallet/Categories";
import { Box, Stack, Wrap, WrapItem } from "@chakra-ui/react";
import CheckcIncomes from "../features/budget/CheckIncomes";
import Screen from "../components/Screen";
import Transactions from "../features/wallet/Transactions";

function Home({ user }) {
  return (
    <div>
      <Head>
        <title>Lumi Budget</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout userName={user?.username || ""} pageTitle="Excelente Día">
        <CheckcIncomes />
        <Stack spacing={8}>
          <BudgetCard />
          <Wrap spacing={8}>
            <WrapItem w={{ base: "100%", lg: "45%" }}>
              <Categories />
            </WrapItem>
            <WrapItem w={{ base: "100%", xl: "45%" }}>
              <Screen title="Transacciones">
                <Transactions />
              </Screen>
            </WrapItem>
          </Wrap>
        </Stack>
      </Layout>
    </div>
  );
}

export default withAuthenticator(Home);
