import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import {
  Container,
  Box,
  Heading,
  Text,
  Center,
  VStack,
  Wrap,
  WrapItem,
} from "@chakra-ui/react";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Lumi Conscious Planning</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Box backgroundColor="#1e5af9" width="full">
          <Container paddingTop="44" paddingBottom="72">
            <Center>
              <VStack spacing={8}>
                <Heading
                  textAlign="center"
                  as="h1"
                  size="4xl"
                  fontWeight="bold"
                  color="white"
                >
                  Lumi Conscious Planning
                </Heading>
                <Text fontSize="lg" color="white" textAlign="center">
                  Omnis nihil quia libero delectus quidem officiis nisi.
                  Adipisci ab nihil aut numquam animi sed. In facere ea.
                  Molestiae esse repellat et. Voluptatum cumque impedit.
                </Text>
              </VStack>
            </Center>
          </Container>
          <Box position="relative" display="flex" justifyContent="center">
            <Box position="absolute" top="-10rem">
              <Wrap>
                <WrapItem paddingTop="6">
                  <Image
                    src="/iphone.png"
                    alt="Vercel Logo"
                    width={167}
                    height={320}
                  />
                </WrapItem>
                <WrapItem>
                  <Image
                    src="/iphone.png"
                    alt="Vercel Logo"
                    width={208}
                    height={400}
                  />
                </WrapItem>
                <WrapItem paddingTop="6">
                  <Image
                    src="/iphone.png"
                    alt="Vercel Logo"
                    width={167}
                    height={320}
                  />
                </WrapItem>
              </Wrap>
            </Box>
          </Box>
        </Box>
        <Container maxW="4xl">
          <Box paddingTop="72">
            <Center>
              <VStack spacing={8}>
                <Heading
                  textAlign="center"
                  as="h2"
                  size="3xl"
                  fontWeight="bold"
                >
                  ¿Quienes somos?
                </Heading>
                <Wrap flexDirection="row">
                  <WrapItem width="40%">
                    <Box display="block" width="16rem">
                      <Image
                        src="/iphone.png"
                        layout="responsive"
                        alt="Vercel Logo"
                        width={208}
                        height={400}
                      />
                    </Box>
                  </WrapItem>
                  <WrapItem
                    width="50%"
                    justifyContent="center"
                    display="flex"
                    flexDirection="column"
                  >
                    <Center>
                      <Text>
                        Aperiam voluptas eos neque. Sed aut odio ea. Odio rerum
                        asperiores illo debitis pariatur deserunt at vel non.
                        Expedita ipsa consequatur ea eius labore quo. Incidunt
                        quia exercitationem ut et soluta. Autem et quis voluptas
                        ut illum unde aliquid quia. Nulla voluptas neque aut
                        tempora sit eaque minima doloribus. Consequatur tempore
                        ipsa aut saepe aut error aut. Quas quo repudiandae ipsam
                        beatae porro hic aut eaque ullam. Est voluptatem aut et
                        temporibus eius quisquam. Accusamus officia delectus at.
                        Maxime quo ut velit dolores sint.
                      </Text>
                    </Center>
                  </WrapItem>
                </Wrap>
              </VStack>
            </Center>
          </Box>
        </Container>
      </main>
    </>
  );
};

export default Home;
