import { useMemo } from "react";
import Head from "next/head";
import { VscAdd } from "react-icons/vsc";
import { withAuthenticator } from "@aws-amplify/ui-react";
import Layout from "../components/Layout";
import { Button, Text, Flex, Wrap, WrapItem } from "@chakra-ui/react";
import Table from "../components/Table";
import Screen from "../components/Screen";

function Transacciones({ user }) {
  const data = useMemo(
    () => [
      {
        id: 1,
        date: "2020-01-01",
        description: "Gasto de mantenimiento",
        amount: -100,
      },
    ],
    []
  );
  const columns = useMemo(
    () => [
      {
        Header: "Fecha",
        accessor: "date",
      },
      {
        Header: "Descripción",
        accessor: "description",
      },
      {
        Header: "Monto",
        accessor: "amount",
      },
    ],
    []
  );
  return (
    <div>
      <Head>
        <title>Lumi Budget</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout userName={user?.username || ""} pageTitle="Mis Proyectos">
        <Wrap spacing={8}>
          <WrapItem width="-moz-fit-content" maxW={{ base: "100%", lg: "50%" }}>
            <Screen
              title="Viaje a Japon"
              description="Distinctio nam eveniet distinctio totam. Voluptatem quaerat tempora fugit quae corrupti. Vel sit beatae placeat quia qui autem fugiat ex."
            >
              <Table data={data} columns={columns} />
            </Screen>
          </WrapItem>
          <WrapItem width="-moz-fit-content" maxW={{ base: "100%", lg: "50%" }}>
            <Screen
              title="Casa"
              description="Esse quasi tempora est minima voluptas blanditiis. Et at et dolor vel. Voluptatibus dolores id id officia iure. Omnis in quia nostrum ipsum. Eius modi qui eligendi beatae. Rerum exercitationem nisi occaecati sapiente minima fuga fugit voluptatem consequatur."
            >
              <Table data={data} columns={columns} />
            </Screen>
          </WrapItem>
          <WrapItem
            width="100%"
            maxW={{ base: "100%", lg: "541px" }}
            minH="123px"
          >
            <Screen>
              <Button
                w="full"
                h="90px"
                color="gray.400"
                colorScheme="whiteAlpha"
                borderWidth="1px"
                borderColor="gray.200"
                borderRadius="md"
                onClick={() => {
                  console.log("click");
                }}
              >
                <Flex direction="column" align="center" justify="center">
                  <VscAdd />
                  <Text>Nuevo</Text>
                </Flex>
              </Button>
            </Screen>
          </WrapItem>
        </Wrap>
      </Layout>
    </div>
  );
}

export default withAuthenticator(Transacciones);
